version: '3.1'

services:

  db:
    hostname: localhost
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    restart: always
    ports:
      - 5432:5432